[package]
name = "outcome_manager"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = "21.4"
soroban-sdk-macros = "21.4"

[dev-dependencies]
soroban-sdk = { version = "21.4", features = ["testutils"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true

[profile.release-with-logs]
inherits = "release"
